### ISSUE TITLE
login สำหรับเจ้าหน้าที่(ลูกจ้างชั่วคราว) จะไม่สามารถใช้งานได้

### ISSUE THREAD

**Issue by EyeOfCode** [pchaow/alumni-spss#21]
![2016-10-26_8-50-24](https://cloud.githubusercontent.com/assets/13258904/19713977/8c035fa0-9b74-11e6-9b96-dc4b8f6fd3b0.jpg)

**Comment by pchaow** [comment]
โดยปกติแล้ว ถ้าเป็น จนท ยังไม่ได้บรรจุ ตอนนี้ยังไม่สามารถเข้าใช้งานได้เพราะไม่ได้มีระบบรองรับ

**Comment by pchaow** [comment]
การแก้ตอนนี้คือปิดความสามารถในการ login สำหรับ จนทที่ไม่มีข้อมูลคณะออกไปก่อน
